// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package accounts

import (
	"context"
	"github.com/fernandodr19/library/pkg/domain/entities/accounts"
	"github.com/fernandodr19/library/pkg/domain/vos"
	"sync"
)

// AccountsMockUsecase is a mock implementation of Usecase.
//
// 	func TestSomethingThatUsesUsecase(t *testing.T) {
//
// 		// make and configure a mocked Usecase
// 		mockedUsecase := &AccountsMockUsecase{
// 			CreateAccountFunc: func(contextMoqParam context.Context, email vos.Email, password vos.Password) (vos.AccID, error) {
// 				panic("mock out the CreateAccount method")
// 			},
// 			GetAccountDetaiilsFunc: func(contextMoqParam context.Context, accID vos.AccID) (accounts.Account, error) {
// 				panic("mock out the GetAccountDetaiils method")
// 			},
// 			LoginFunc: func(contextMoqParam context.Context, email vos.Email, password vos.Password) (vos.AccID, vos.Tokens, error) {
// 				panic("mock out the Login method")
// 			},
// 		}
//
// 		// use mockedUsecase in code that requires Usecase
// 		// and then make assertions.
//
// 	}
type AccountsMockUsecase struct {
	// CreateAccountFunc mocks the CreateAccount method.
	CreateAccountFunc func(contextMoqParam context.Context, email vos.Email, password vos.Password) (vos.AccID, error)

	// GetAccountDetaiilsFunc mocks the GetAccountDetaiils method.
	GetAccountDetaiilsFunc func(contextMoqParam context.Context, accID vos.AccID) (accounts.Account, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(contextMoqParam context.Context, email vos.Email, password vos.Password) (vos.AccID, vos.Tokens, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateAccount holds details about calls to the CreateAccount method.
		CreateAccount []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Email is the email argument value.
			Email vos.Email
			// Password is the password argument value.
			Password vos.Password
		}
		// GetAccountDetaiils holds details about calls to the GetAccountDetaiils method.
		GetAccountDetaiils []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// AccID is the accID argument value.
			AccID vos.AccID
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Email is the email argument value.
			Email vos.Email
			// Password is the password argument value.
			Password vos.Password
		}
	}
	lockCreateAccount      sync.RWMutex
	lockGetAccountDetaiils sync.RWMutex
	lockLogin              sync.RWMutex
}

// CreateAccount calls CreateAccountFunc.
func (mock *AccountsMockUsecase) CreateAccount(contextMoqParam context.Context, email vos.Email, password vos.Password) (vos.AccID, error) {
	callInfo := struct {
		ContextMoqParam context.Context
		Email           vos.Email
		Password        vos.Password
	}{
		ContextMoqParam: contextMoqParam,
		Email:           email,
		Password:        password,
	}
	mock.lockCreateAccount.Lock()
	mock.calls.CreateAccount = append(mock.calls.CreateAccount, callInfo)
	mock.lockCreateAccount.Unlock()
	if mock.CreateAccountFunc == nil {
		var (
			accIDOut vos.AccID
			errOut   error
		)
		return accIDOut, errOut
	}
	return mock.CreateAccountFunc(contextMoqParam, email, password)
}

// CreateAccountCalls gets all the calls that were made to CreateAccount.
// Check the length with:
//     len(mockedUsecase.CreateAccountCalls())
func (mock *AccountsMockUsecase) CreateAccountCalls() []struct {
	ContextMoqParam context.Context
	Email           vos.Email
	Password        vos.Password
} {
	var calls []struct {
		ContextMoqParam context.Context
		Email           vos.Email
		Password        vos.Password
	}
	mock.lockCreateAccount.RLock()
	calls = mock.calls.CreateAccount
	mock.lockCreateAccount.RUnlock()
	return calls
}

// GetAccountDetaiils calls GetAccountDetaiilsFunc.
func (mock *AccountsMockUsecase) GetAccountDetaiils(contextMoqParam context.Context, accID vos.AccID) (accounts.Account, error) {
	callInfo := struct {
		ContextMoqParam context.Context
		AccID           vos.AccID
	}{
		ContextMoqParam: contextMoqParam,
		AccID:           accID,
	}
	mock.lockGetAccountDetaiils.Lock()
	mock.calls.GetAccountDetaiils = append(mock.calls.GetAccountDetaiils, callInfo)
	mock.lockGetAccountDetaiils.Unlock()
	if mock.GetAccountDetaiilsFunc == nil {
		var (
			accountOut accounts.Account
			errOut     error
		)
		return accountOut, errOut
	}
	return mock.GetAccountDetaiilsFunc(contextMoqParam, accID)
}

// GetAccountDetaiilsCalls gets all the calls that were made to GetAccountDetaiils.
// Check the length with:
//     len(mockedUsecase.GetAccountDetaiilsCalls())
func (mock *AccountsMockUsecase) GetAccountDetaiilsCalls() []struct {
	ContextMoqParam context.Context
	AccID           vos.AccID
} {
	var calls []struct {
		ContextMoqParam context.Context
		AccID           vos.AccID
	}
	mock.lockGetAccountDetaiils.RLock()
	calls = mock.calls.GetAccountDetaiils
	mock.lockGetAccountDetaiils.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *AccountsMockUsecase) Login(contextMoqParam context.Context, email vos.Email, password vos.Password) (vos.AccID, vos.Tokens, error) {
	callInfo := struct {
		ContextMoqParam context.Context
		Email           vos.Email
		Password        vos.Password
	}{
		ContextMoqParam: contextMoqParam,
		Email:           email,
		Password:        password,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	if mock.LoginFunc == nil {
		var (
			accIDOut  vos.AccID
			tokensOut vos.Tokens
			errOut    error
		)
		return accIDOut, tokensOut, errOut
	}
	return mock.LoginFunc(contextMoqParam, email, password)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//     len(mockedUsecase.LoginCalls())
func (mock *AccountsMockUsecase) LoginCalls() []struct {
	ContextMoqParam context.Context
	Email           vos.Email
	Password        vos.Password
} {
	var calls []struct {
		ContextMoqParam context.Context
		Email           vos.Email
		Password        vos.Password
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}
